### ISSUE TITLE
[BLOCK] UrbanVPN

### ISSUE THREAD

**Issue by itsfolf** [Ealenn/AdGuard-Home-List#42]
**Describe**
The urban-vpn.com extensions constantly phone home tracking every website visited by the user, including full URL, headers, browser info, and a lot more.
This is pretty much malware and should be in some mainstream blocklist, but I have no clue where to report it.

**Domain**
```
||analytics-toolbar.urban-vpn.com^
||anti-mining-protection-toolbar.urban-vpn.com^
```

**Comment by Ealenn** [comment]
Hello @fuwwy 

Thanks for this contribution. This blocklist isn't adopted by many people. It's not a standard, it's just mine.
It gathers a lot of popular lists, and adds some rules on top.

If you want to share your discovery with as many people as possible, I invite you to find a popular list in the links of the readme (like [notracking/hosts-blocklists](https://github.com/notracking/hosts-blocklists)).

Either way, I'll add this to my list. I think it's legitimate to block these calls.
Let me test on my side, and push the new rules.

Thanks 🙏
