### ISSUE TITLE
[BUG] Can't add block list to adguard home

### ISSUE THREAD

**Issue by m4rf3d** [Ealenn/AdGuard-Home-List#49]
**Describe the bug**
Hi. I can't add your block list to adguard home (allow list is warking). I get an error: Error: control/filtering/add_url | Couldn't fetch filter from URL "https://raw.githubusercontent.com/Ealenn/AdGuard-Home-List/gh-pages/AdGuard-Home-List.Block.txt": line 2278706: character 16: likely binary character '\x00' | 400
It worked about 2 weeks ago.
Can you help me?

![Zrzut ekranu 2023-08-3 o 10 12 54](https://github.com/Ealenn/AdGuard-Home-List/assets/124442910/0f17f54c-5c06-4eee-9045-89f20a6adedf)

**Comment by Ealenn** [comment]
Hi ! Thanks for your report !
Indeed I had the same error... I have to generate the lists locally to see which aggregate generate bad character. 

I'll keep you informed

**Comment by m4rf3d** [comment]
Thank you!

**Comment by Ealenn** [comment]
Hi @m4rf3d 
Should be good now ;) Sorry for the delay

**Comment by m4rf3d** [comment]
@Ealenn Thank you.
It' working now.
